name: Kernel CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Kernel Source
      uses: actions/checkout@v2

    - name: Getting Toolchain
      run: |
        sudo apt-get install lib32z1 ccache autoconf
        sudo git clone --depth 1 --branch master --single-branch https://github.com/STS-Dev-Team/arm-eabi-4.4.3 /opt/toolchains/arm-eabi-4.4.3/
    - name: Building Kernel
      run: |
        export KBUILD_BUILD_USER=notnoelchannel
        export KBUILD_BUILD_HOST=unlegacy-devices
        make -j22 ARCH=arm CROSS_COMPILE=/opt/toolchains/arm-eabi-4.4.3/ cyanogenmod_e0_defconfig
        make oldconfig
        make -j12
    - name: Moving Output # CI only
      run: |
        mkdir -p /home/runner/work/output
        cp arch/arm/boot/Image /home/runner/work/output/zImage
    - name: Uploading Output
      uses: actions/upload-artifact@v2
      with:
        name: zImage
        path: /home/runner/work/output/zImage
